### ISSUE TITLE
What's It Like Working With keokilee?

### ISSUE THREAD

**Issue by keokilee** [micjamking/ama#2]
I mean, is he a jerk or what?

**Comment by micjamking** [comment]
## My second question!! :zap:

Honestly, he's the only person I've ever known that has... 
a.) gone to PAX and 
b.) brought me Magic cards (:neckbeard:) back from PAX 
...so there's that. 

![fullsizerender 1](https://cloud.githubusercontent.com/assets/651702/9682005/49c37bea-529e-11e5-9353-2319270b429c.jpg)

_(He gets +1500 & a squirrel pin from me for :point_up:)_

:confused: hmmmm... let's see, what else...

...I think he knows [JavaScript](https://twitter.com/keokilee/status/635265428781051904)? Not too sure, but [some folks](https://www.facebook.com/groups/ohanajs/) seem to agree... Honestly, I'm not sure what he does all day besides coming up with [crazy ideas to keep ramen noodles from getting cold](https://twitter.com/keokilee/status/634182130721886208). I occasionally worry that he doesn't get out of the office much, and when he does, [the office comes with him](https://instagram.com/p/4cn87mwVdZ/). Also, I have the haunting suspicion that he's deeply invested with Nabisco and is trying to [retire early, from the support of our office](https://instagram.com/p/4Co7EWwVV2). Besides that, he's generally an alright dude and awesome guy to work with, just don't ask him for help with maths; he's good, [but he can be a prick about it](https://twitter.com/keokilee/status/632013325086257152).
